language: go # 声明构建语言环境
sudo: false

go:
  - 1.17.8

install: #依赖安装
  #- go get golang.org/x/tools/cmd/cover
  #- go get github.com/mattn/goveralls

script: # 集成脚本
    - go test -v -race -coverprofile=coverage.txt -covermode=atomic --cover ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

env: #env环境变量设置，travis提供的repo_token安全方式
  global:
    GO111MODULE: "on"
